<Button>
    font_size: 32
    background_normal: ''
    background_color: (0,0,1,1)

<Label>
    font_size: 32

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 10
        spacing: 10

        Label:
            id: label_out
            text: "Name"

        Button:
            text: "Finding"
            background_color: (0,0.5,0.2)
            on_press: root.press()